[package]
name = "motologo"
version = "0.1.0"
authors = ["Sebastian Wagner <sw2000@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
